#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: _GLA-CMN | install | Add glance group
  become: yes
  group: name={{ glance_system_group }}

# this creates the getent_passwd fact enumerating the existing users
- name: _GLA-CMN | install | Check if user already exists
  getent:
    database: passwd

- name: _GLA-CMN | install | Create glance user if it doesn't exist
  become: yes
  user:
    name: "{{ glance_system_user }}"
    group: "{{ glance_system_group }}"
    createhome: "{{ glance_system_createhome }}"
    home: "{{ glance_home_dir }}"
    shell: "{{ glance_system_shell }}"
  when:
    - glance_system_user not in getent_passwd

- name: _GLA-CMN | install | Move existing home dir if needed
  become: yes
  user:
    name: "{{ glance_system_user }}"
    group: "{{ glance_system_group }}"
    move_home: yes
    home: "{{ glance_home_dir }}"
    shell: "{{ glance_system_shell }}"
  when:
    - glance_system_user in getent_passwd
    - getent_passwd[glance_system_user][4] != glance_home_dir
  register: glance_user_move_home_result
  failed_when:
    - glance_user_move_home_result | failed
    - ("user " ~ glance_system_user ~ " is currently used by process"
       not in glance_user_move_home_result.msg)

- name: _GLA-CMN | install | Set flag to indicate start needs to try this
  stat:
    path: /dev/null
  changed_when: true
  register: ardana_notify_glance_user_home_move_needed
  when:
    - glance_user_move_home_result is defined
    - glance_user_move_home_result.msg is defined
    - ("user " ~ glance_system_user ~ " is currently used by process"
       in glance_user_move_home_result.msg)

# NOTE: Matching the creation of home dir with glance RPM package
# openstack-glance
- name: _GLA-CMN | install | Create user home
  become: yes
  file:
    path: "{{ glance_home_dir }}"
    state: directory
    owner: "{{ glance_system_user }}"
    group: "{{ glance_system_group }}"
    mode: 0755
